name: WEBSERV CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/*, fix/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo "hello"
